x-app: &default-app
  build:
    context: .
    dockerfile: ./docker/backend/Dockerfile
    args:
      BUILD_ENVIRONMENT: "${DOCKER_BUILD_ENVIRONMENT:-production}"
    cache_from:
      - "${DOCKER_BUILD_IMAGE_PREFIX}/backend:latest"

  image: "${DOCKER_BUILD_IMAGE_PREFIX}/backend:${DOCKER_BUILD_IMAGE_TAG:-latest}"
  depends_on:
    - postgres
  environment:
    - ALLOWED_HOSTS
    - CSRF_TRUSTED_ORIGINS
    - ADMIN_URL
    - STATIC_URL
    - POSTGRES_HOST
    - POSTGRES_PORT
    - POSTGRES_DB
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - DEBUG
    - SECRET_KEY
    - GOOGLE_CLIENT_ID
    - GOOGLE_CLIENT_SECRET
    - CELERY_FLOWER_USER
    - CELERY_FLOWER_PASSWORD
    - CELERY_BROKER_URL

services:
  caddy:
    build:
      context: .
      dockerfile: ./docker/caddy/Dockerfile
      cache_from:
        - "${DOCKER_BUILD_IMAGE_PREFIX}/caddy:latest"

    image: "${DOCKER_BUILD_IMAGE_PREFIX}/caddy:${DOCKER_BUILD_IMAGE_TAG:-latest}"
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "${DOCKER_CADDY_PORT_FORWARD:-80}:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - SITE_ADDRESS

  backend:
    <<: *default-app
    command: /start_django

  celery-worker:
    <<: *default-app
    command: /start_celeryworker

  celery-beat:
    <<: *default-app
    depends_on:
      - backend
    command: /start_celerybeat

  flower:
    <<: *default-app
    command: /start_flower

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
      args:
        BUILD_ENVIRONMENT: "${DOCKER_BUILD_ENVIRONMENT:-production}"
      cache_from:
        - "${DOCKER_BUILD_IMAGE_PREFIX}/frontend:latest"

    image: "${DOCKER_BUILD_IMAGE_PREFIX}/frontend:${DOCKER_BUILD_IMAGE_TAG:-latest}"
    command: /start
    environment:
      - NEXT_PUBLIC_BACKEND_URL
      - NEXTAUTH_GOOGLE_CLIENT_ID
      - NEXTAUTH_GOOGLE_CLIENT_SECRET
      - NEXTAUTH_URL
      - NEXTAUTH_SECRET

  postgres:
    image: docker.io/postgres:12.6
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  redis:
    image: docker.io/redis:6.0

volumes:
  caddy_data:
  caddy_config:
  production_postgres_data: {}
