x-app: &default-app
  build:
    context: .
    dockerfile: ./docker/django/Dockerfile
    args:
      BUILD_ENVIRONMENT: "${DOCKER_BUILD_ENVIRONMENT:-production}"
  image: "${DOCKER_BUILD_IMAGE_PREFIX}/django"
  depends_on:
    - postgres
  environment:
    - ALLOWED_HOSTS
    - ADMIN_URL
    - STATIC_URL
    - POSTGRES_HOST
    - POSTGRES_PORT
    - POSTGRES_DB
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - DEBUG
    - SECRET_KEY

services:
  caddy:
    build:
      context: .
      dockerfile: ./docker/caddy/Dockerfile
      cache_from:
        - "${DOCKER_BUILD_IMAGE_PREFIX}/caddy:latest"

    image: "${DOCKER_BUILD_IMAGE_PREFIX}/caddy"
    restart: unless-stopped
    depends_on:
      - django
    ports:
      - "${DOCKER_CADDY_PORT_FORWARD:-80}:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - SITE_ADDRESS

  django:
    <<: *default-app
    build:
      cache_from:
        - "${DOCKER_BUILD_IMAGE_PREFIX}/caddy:latest"
    command: /start

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
      args:
        BUILD_ENVIRONMENT: "${DOCKER_BUILD_ENVIRONMENT:-production}"
      cache_from:
        - "${DOCKER_BUILD_IMAGE_PREFIX}/frontend:latest"

    image: "${DOCKER_BUILD_IMAGE_PREFIX}/frontend"
    command: /start

  postgres:
    image: docker.io/postgres:12.6
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  redis:
    image: docker.io/redis:5.0

volumes:
  caddy_data:
  caddy_config:
  production_postgres_data: {}
