resources:
  - k8s/namespace.yml
  - k8s/deployments.yml
  - k8s/jobs.yml
  - k8s/services.yml
  - k8s/volumes.yml
  - k8s/ingress.yml

namespace: web-template

configMapGenerator:
  - name: frontend-config
    literals:
      - NEXT_PUBLIC_BACKEND_URL=$PROD_NEXT_PUBLIC_BACKEND_URL
      - NEXTAUTH_URL=$PROD_NEXTAUTH_URL

  - name: backend-config
    literals:
      - ALLOWED_HOSTS=$PROD_ALLOWED_HOSTS
      - SITE_ADDRESS=$PROD_SITE_ADDRESS
      - DEBUG=$PROD_DEBUG
      - CELERY_BROKER_URL=$PROD_CELERY_BROKER_URL

secretGenerator:
  - name: frontend-secrets
    literals:
      - NEXTAUTH_GOOGLE_CLIENT_ID=$PROD_NEXTAUTH_GOOGLE_CLIENT_ID
      - NEXTAUTH_GOOGLE_CLIENT_SECRET=$PROD_NEXTAUTH_GOOGLE_CLIENT_SECRET

  - name: backend-secrets
    literals:
      - ADMIN_URL=$PROD_ADMIN_URL
      - STATIC_URL=$PROD_STATIC_URL
      - POSTGRES_HOST=$PROD_POSTGRES_HOST
      - POSTGRES_PORT=$PROD_POSTGRES_PORT
      - POSTGRES_DB=$PROD_POSTGRES_DB
      - POSTGRES_USER=$PROD_POSTGRES_USER
      - POSTGRES_PASSWORD=$PROD_POSTGRES_PASSWORD
      - SECRET_KEY=$PROD_SECRET_KEY
      - GOOGLE_CLIENT_ID=$PROD_GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET=$PROD_GOOGLE_CLIENT_SECRET
      - CELERY_FLOWER_USER=$PROD_CELERY_FLOWER_USER
      - CELERY_FLOWER_PASSWORD=$PROD_CELERY_FLOWER_PASSWORD

  - name: postgres-secrets
    literals:
      - POSTGRES_DB=$PROD_POSTGRES_DB
      - POSTGRES_USER=$PROD_POSTGRES_USER
      - POSTGRES_PASSWORD=$PROD_POSTGRES_PASSWORD

  - name: regcred
    literals:
      - .dockerconfigjson=$PROD_DOCKER_CONFIG_JSON
    type: kubernetes.io/dockerconfigjson

images:
  - name: backend
    newName: $CI_REGISTRY_IMAGE/backend:latest
  - name: frontend
    newName: $CI_REGISTRY_IMAGE/frontend:latest

vars:
  - name: SITE_ADDRESS
    objref:
      kind: ConfigMap
      name: backend-config
      apiVersion: v1
    fieldref:
      fieldpath: data.SITE_ADDRESS
