version: '3.7'

volumes:
  production_postgres_data: {}
  caddy_data:
  caddy_config:

services:
  caddy:
    build:
      context: .
      dockerfile: ./docker/caddy/Dockerfile
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "8123:80"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - SITE_ADDRESS
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      args:
        BUILD_ENVIRONMENT: development
    image: application_web
    depends_on:
      - postgres
      - mailhog
    volumes:
      - ./application:/application:z
    command: /start
    env_file:
      - .env

  postgres:
    image: postgres:12.6
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  redis:
    image: redis:5.0

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "8025:8025"

  docs:
    build:
      context: .
      dockerfile: ./docker/docs/Dockerfile
    image: application_docs
    volumes:
      - ./docs:/docs:z
    ports:
      - "8124:8124"
    command: /start-docs

  swagger:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8125:8080"
    environment:
      - SWAGGER_JSON=/schema.yml
    volumes:
      - ./application/schema.yml:/schema.yml
