- name: Create user account.
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    comment: "{{ username }} system user"
    createhome: yes
    shell: /bin/false
    password: '*'
    state: present

- name: Register {{ username }} user info.
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
  check_mode: true
  register: docker_user_info

- name: Ensure {{ username }} user is lingering.
  ansible.builtin.stat:
    path: "/var/lib/systemd/linger/{{ username }}"
  register: docker_user_lingering

- name: Enable lingering for {{ username }} user.
  become: true
  ansible.builtin.command:
    cmd: "loginctl enable-linger {{ username }}"
  register: enable_lingering
  changed_when: enable_lingering.rc != 0
  failed_when: enable_lingering.rc != 0
  when: not docker_user_lingering.stat.exists

- name: Stat Docker user docker.sock
  become: true
  become_user: "{{ username }}"
  ansible.builtin.stat:
    path: "/run/user/{{ docker_user_info.uid }}/docker.sock"
  register: docker_rootless_sock

- name: Install uidmap
  become: true
  ansible.builtin.package:
    name: uidmap
    state: present
  when: not docker_rootless_sock.stat.exists

- name: Install rootless docker
  become: true
  become_user: "{{ username }}"
  environment:
    PATH: "{{ docker_user_info.home }}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    XDG_RUNTIME_DIR: "/run/user/{{ docker_user_info.uid }}"
  ansible.builtin.command:
    cmd: dockerd-rootless-setuptool.sh install
  register: install_rootless_docker
  changed_when: install_rootless_docker.rc != 0
  failed_when: install_rootless_docker.rc != 0
  when: not docker_rootless_sock.stat.exists

- name: Add Docker systemd service.
  become: true
  become_user: "{{ username }}"
  ansible.builtin.template:
    src: docker_rootless.service.j2
    dest: "{{ docker_user_info.home }}/.config/systemd/user/docker.service"
    backup: true
    mode: "0600"

- name: Enable and start Docker.
  become: true
  become_user: "{{ username }}"
  ansible.builtin.systemd:
    name: docker.service
    enabled: true
    state: started
    scope: user
    daemon_reload: true
