#cloud-config
users:
  - name: ubuntu
    ssh-authorized-keys:
      - ${init_ssh_public_key}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups:
      - sudo
    shell: /bin/bash
 
runcmd:
  - sed -i 's/PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config
  - echo "Port 4444" >> /etc/ssh/sshd_config
  - echo "AllowUsers ubuntu" >> /etc/ssh/sshd_config
  - systemctl restart ssh
