- name: Commons
  hosts: web_template
  vars_files:
    - ../variables.yml
  roles:
    - role: geerlingguy.docker
      become: true
      tags: docker
      vars:
        docker_users:
          - ubuntu
