site_name: WebTemplate
site_url: https://example.com/
docs_dir: pages
dev_addr: 0.0.0.0:8124
nav:
    - Misc: index.md
    - Management commands: management.md
    - Dependencies upgrade: dependencies_upgrade.md
theme: readthedocs
