site_name: WebTemplate
site_url: https://example.com/
docs_dir: pages
dev_addr: 0.0.0.0:8124
nav:
    - Main: index.md
    - Dependencies upgrade: dependencies_upgrade.md
    - API client upgrade: api_client_upgrade.md
    - Frontend upgrade: frontend_upgrade.md
    - Frontend notes: frontend_notes.md
    - Google OAuth configuration: google_oauth.md
theme:
    name: material
