site_name: WebTemplate
site_url: https://example.com/
docs_dir: pages
dev_addr: 0.0.0.0:8124
nav:
    - Main: index.md
    - Management commands: management_commands.md
    - Dependencies upgrade: dependencies_upgrade.md
    - API client upgrade: api_client_upgrade.md
theme: readthedocs
